spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCTS
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: E-CommerceCircuitBreaker
                fallbackUri: forward:/productServiceFallback
            - RewritePath=/product(?<segment>/?.*),/api/product${segment}

        - id: user-service
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*),/api/users${segment}

        - id: order-service
          uri: lb://ORDERS
          predicates:
            - Path=/orders/**
            - Path=/cart/**
          filters:
            - RewritePath=/(?<segment>.*),/api/${segment}

        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampler:
      probability: 1.0

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
