spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDERS
          predicates:
            - Path=/api/orders/** ,/api/cart/**
        - id: product-service
          uri: lb://PRODUCTS
          predicates:
            - Path=/api/product/**
        - id: user-service
          uri: lb://USERS
          predicates:
            - Path=/api/users/**
        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**


management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampler:
      probability: 1.0



server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  register-with-eureka: true
  fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
