spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Order_DataBase
    username: Hemanth
    password: 9705830040@Chk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      bindings:
        createOrder-out-0:
          destination: order.exchange
          contentType: application/json
          producer:
            routing-key: '''order.tracking'''

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

app:
  message: "This is Order Microservice from Git application.yml config"
