spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Product_DataBase
    username: Hemanth
    password: 9705830040@Chk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

app:
  message: "This is Product Microservice from Git appliaction.yml config"
